### PR TITLE
enable positioning

### PR DESCRIPTION
**Pull request by McHaillet**
The default setting already disables positioning, so currently it is not possible to do automatic positioning.
Changing default to False, gives the correct behavior.

### CODE REVIEW

**Comment by bwmr** [comment]
Hi Marten, 
You're completely right, I overlooked this when switching the default behavior to not doing positioning. In my opinion, this should stay the default. I'd suggest adding the inverse flag, e.g. `--do-positioning/--skip-positioning`, similar to how it works for patch / global frame alignment:

`@click.option(
    "--patch/--global",
    is_flag=True,
    default=False,
    show_default=True,
    help="Perform full-frame or patch alignment.",
)`

**Comment by bwmr** [comment]
Implemented as discussed in commit [7ebb503](https://github.com/tomotools/tomotools/commit/7ebb50358b9794ea2ba2f2ba7f30464bf08acc70). 

@McHaillet could you test whether this performs according to your needs? The `reconstruct --do-positioning` should now work, default is still `skip-positioning`. Then I'd close this PR.

**Comment by McHaillet** [comment]
Hi Benedikt! Of course, I will give it a test on monday!

**Comment by bwmr** [comment]
Thanks for testing it! I haven't had this issue with my K2 tomograms, maybe it is related to your (rather small) tomogram dimensions? The command should reconstruct the tomogram at bin 8 for finding the positioning (which would be 64 x 64 x 31 for your data), maybe that's related? 
Anyways, I'll close this PR now and if you could put it in a separate issue that would be great.

**Pull request closed without merging**
